import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Sidebar from '@/components/Sidebar'
import BottomNavbar from '@/components/BottomNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='h-100% relative'>
          <Header/>
          <div className='max-w-screen-xl m-auto flex gap-6'>
            {children}
          </div>
          <BottomNavbar/>
        </div>
      </body>
    </html>
  )
}
